-- Corrects the built-in recipe facets seeded by migration 892.
--
-- 892 derived every category from Open Design's coarse `od.scenario` bucket.
-- That was the wrong field: decks carry their own `od.category`, which is the
-- taxonomy the Open Design community tab actually filters by (融资路演,
-- 企业战略, B2B 销售 …), and the scenario bucket collapsed all fifteen of them
-- into a handful of invented labels.
--
-- Categories now come from `od.category` where the source declares one, and
-- fall back to the scenario bucket only for the modes that carry none. Labels
-- are Open Design's own zh strings rather than a re-translation.
--
-- Written as UPDATEs against 892's rows: 892 is already applied, and a seed
-- migration is never edited in place.
UPDATE design_scenario_recipe AS r SET
    category = v.category,
    subcategory = v.subcategory,
    updated_at = now()
FROM (VALUES
    ('doc-kami-parchment', '个人主页', '网页'),
    ('social-spotify-card', '个人主页', '网页'),
    ('resume-modern', '个人主页', '网页'),
    ('gamified-app', '个人主页', '网页'),
    ('dating-web', '个人主页', '网页'),
    ('mockup-device-3d', '产品管理', '网页'),
    ('pm-spec', '产品管理', '网页'),
    ('team-okrs', '产品管理', '网页'),
    ('eng-runbook', '开发者工具', '网页'),
    ('web-clone', '开发者工具', '网页'),
    ('codex-interactive-capability-map', '教育培训', '网页'),
    ('invoice', '数据与财务', '网页'),
    ('data-report', '数据与财务', '网页'),
    ('finance-report', '数据与财务', '网页'),
    ('kami-landing', '落地页与营销', '网页'),
    ('motion-frames', '落地页与营销', '网页'),
    ('open-design-homepage', '落地页与营销', '网页'),
    ('open-design-landing', '落地页与营销', '网页'),
    ('social-reddit-card', '落地页与营销', '网页'),
    ('card-twitter', '落地页与营销', '网页'),
    ('social-x-post-card', '落地页与营销', '网页'),
    ('pricing-page', '落地页与营销', '网页'),
    ('blog-post', '落地页与营销', '网页'),
    ('card-xiaohongshu', '落地页与营销', '网页'),
    ('digital-eguide', '落地页与营销', '网页'),
    ('article-magazine', '落地页与营销', '网页'),
    ('magazine-poster', '落地页与营销', '网页'),
    ('email-marketing', '落地页与营销', '网页'),
    ('social-carousel', '落地页与营销', '网页'),
    ('waitlist-page', '落地页与营销', '网页'),
    ('sprite-animation', '落地页与营销', '网页'),
    ('poster-hero', '落地页与营销', '网页'),
    ('clinical-case-report', '行业场景', '网页'),
    ('hr-onboarding', '行业场景', '网页'),
    ('dcf-valuation', '设计与创意', '网页'),
    ('html-ppt-taste-brutalist', '设计与创意', '网页'),
    ('html-ppt-taste-editorial', '设计与创意', '网页'),
    ('velar-luxury-real-estate', '设计与创意', '网页'),
    ('webgl-voronoi-cells', '设计与创意', '网页'),
    ('web-prototype-taste-brutalist', '设计与创意', '网页'),
    ('web-prototype-taste-soft', '设计与创意', '网页'),
    ('web-prototype-taste-editorial', '设计与创意', '网页'),
    ('webgl-experience', '设计与创意', '网页'),
    ('worker-visualizer', '设计与创意', '网页'),
    ('x-research', '设计与创意', '网页'),
    ('webgl-pixel-reveal-gallery', '设计与创意', '网页'),
    ('webgl-raymarched-hero', '设计与创意', '网页'),
    ('webgl-holographic-foil', '设计与创意', '网页'),
    ('webgl-halftone-drift', '设计与创意', '网页'),
    ('webgl-distortion-grain', '设计与创意', '网页'),
    ('tweaks', '设计与创意', '网页'),
    ('last30days', '设计与创意', '网页'),
    ('webgl-aurora-veil', '设计与创意', '网页'),
    ('wireframe-annotated', '设计与创意', '网页'),
    ('webgl-horizontal-parallax', '设计与创意', '网页'),
    ('webgl-caustic-pool', '设计与创意', '网页'),
    ('webgl-liquid-metal', '设计与创意', '网页'),
    ('webgl-depth-gallery', '设计与创意', '网页'),
    ('wireframe-greybox', '设计与创意', '网页'),
    ('social-media-dashboard', '设计与创意', '网页'),
    ('mobile-app', '设计与创意', '网页'),
    ('wireframe-mobile-flow', '设计与创意', '网页'),
    ('webgl-particle-galaxy', '设计与创意', '网页'),
    ('wireframe-sketch', '设计与创意', '网页'),
    ('webgl-liquid-iridescence', '设计与创意', '网页'),
    ('critique', '设计与创意', '网页'),
    ('webgl-neon-grid', '设计与创意', '网页'),
    ('flowai-live-dashboard-template', '运营与看板', '网页'),
    ('github-dashboard', '运营与看板', '网页'),
    ('orbit-github', '运营与看板', '网页'),
    ('orbit-gmail', '运营与看板', '网页'),
    ('orbit-linear', '运营与看板', '网页'),
    ('orbit-notion', '运营与看板', '网页'),
    ('orbit-general', '运营与看板', '网页'),
    ('dashboard', '运营与看板', '网页'),
    ('meeting-notes', '运营与看板', '网页'),
    ('live-dashboard', '运营与看板', '网页'),
    ('live-artifact', '运营与看板', '网页'),
    ('kanban-board', '运营与看板', '网页'),
    ('html-ppt-tech-sharing', 'AI 素养', '网页'),
    ('html-ppt-obsidian-claude-gradient', 'AI 素养', '网页'),
    ('html-ppt-presenter-mode-reveal', 'AI 素养', '网页'),
    ('html-ppt-hermes-cyber-terminal', 'AI 素养', '网页'),
    ('ve-terminal-mono', 'AI 素养', '网页'),
    ('frontend-slides', 'AI 素养', '网页'),
    ('fs-electric-studio', 'B2B 销售', '网页'),
    ('huashu-takram-soft-tech', 'B2B 销售', '网页'),
    ('html-ppt-zhangzara-cobalt-grid', 'B2B 销售', '网页'),
    ('html-ppt-product-launch', 'B2B 销售', '网页'),
    ('huashu-bento-insight', 'B2B 销售', '网页'),
    ('html-ppt-graphify-dark-graph', '产品管理', '网页'),
    ('replit-deck', '产品管理', '网页'),
    ('deck-open-slide-canvas', '产品管理', '网页'),
    ('html-ppt-knowledge-arch-blueprint', '产品管理', '网页'),
    ('hps-true-blueprint', '产品管理', '网页'),
    ('html-ppt', '企业战略', '网页'),
    ('huashu-keynote-black', '企业战略', '网页'),
    ('huashu-annual-letter', '企业战略', '网页'),
    ('simple-deck', '企业战略', '网页'),
    ('html-ppt-zhangzara-blue-professional', '企业战略', '网页'),
    ('html-ppt-zhangzara-signal', '企业战略', '网页'),
    ('deck-swiss-international', '企业战略', '网页'),
    ('html-ppt-zhangzara-soft-editorial', '咨询顾问', '网页'),
    ('ppt-keynote', '咨询顾问', '网页'),
    ('huashu-golden-circle', '咨询顾问', '网页'),
    ('huashu-luxe-whitespace', '咨询顾问', '网页'),
    ('html-ppt-zhangzara-mat', '咨询顾问', '网页'),
    ('html-ppt-zhangzara-monochrome', '学术研究', '网页'),
    ('html-ppt-zhangzara-vellum', '学术研究', '网页'),
    ('kami-deck', '学术研究', '网页'),
    ('hps-academic-paper', '学术研究', '网页'),
    ('html-ppt-zhangzara-scatterbrain', '学生作业', '网页'),
    ('html-ppt-zhangzara-cartesian', '学生作业', '网页'),
    ('html-ppt-zhangzara-pin-and-paper', '学生作业', '网页'),
    ('fs-notebook-tabs', '学生作业', '网页'),
    ('deck-guizang-editorial', '市场增长', '网页'),
    ('open-design-landing-deck', '市场增长', '网页'),
    ('html-ppt-zhangzara-broadside', '市场增长', '网页'),
    ('huashu-pentagram-grid', '市场增长', '网页'),
    ('fs-emerald-editorial', '市场增长', '网页'),
    ('html-ppt-zhangzara-coral', '市场增长', '网页'),
    ('html-ppt-zhangzara-peoples-platform', '政府与政策', '网页'),
    ('html-ppt-zhangzara-grove', '政府与政策', '网页'),
    ('html-ppt-zhangzara-stencil-tablet', '政府与政策', '网页'),
    ('html-ppt-testing-safety-alert', '政府与政策', '网页'),
    ('html-ppt-zhangzara-long-table', '数据与财务', '网页'),
    ('html-ppt-weekly-report', '数据与财务', '网页'),
    ('ve-midnight-editorial', '数据与财务', '网页'),
    ('weekly-update', '数据与财务', '网页'),
    ('hps-y2k-chrome', '数据与财务', '网页'),
    ('huashu-sparkline-arc', '数据与财务', '网页'),
    ('hps-memphis-pop', '生活故事', '网页'),
    ('html-ppt-xhs-pastel-card', '生活故事', '网页'),
    ('html-ppt-zhangzara-pink-script', '生活故事', '网页'),
    ('html-ppt-zhangzara-sakura-chroma', '生活故事', '网页'),
    ('html-ppt-zhangzara-8-bit-orbit', '生活故事', '网页'),
    ('html-ppt-zhangzara-retro-zine', '生活故事', '网页'),
    ('hps-retro-tv', '生活故事', '网页'),
    ('html-ppt-zhangzara-neo-grid-bold', '职业发展', '网页'),
    ('html-ppt-zhangzara-capsule', '职业发展', '网页'),
    ('html-ppt-xhs-white-editorial', '职业发展', '网页'),
    ('huashu-slides', '职业发展', '网页'),
    ('html-ppt-zhangzara-retro-windows', '职业培训', '网页'),
    ('hps-bauhaus', '职业培训', '网页'),
    ('html-ppt-zhangzara-daisy-days', '职业培训', '网页'),
    ('html-ppt-course-module', '职业培训', '网页'),
    ('html-ppt-zhangzara-playful', '职业培训', '网页'),
    ('guizang-ppt', '落地页与营销', '网页'),
    ('html-ppt-zhangzara-bold-poster', '融资路演', '网页'),
    ('ib-pitch-book', '融资路演', '网页'),
    ('fs-creative-voltage', '融资路演', '网页'),
    ('html-ppt-pitch-deck', '融资路演', '网页'),
    ('html-ppt-zhangzara-creative-mode', '设计打磨', '网页'),
    ('html-ppt-zhangzara-studio', '设计打磨', '网页'),
    ('fs-editorial-forest', '设计打磨', '网页'),
    ('html-ppt-zhangzara-editorial-tri-tone', '设计打磨', '网页'),
    ('html-ppt-zhangzara-biennale-yellow', '设计打磨', '网页'),
    ('html-ppt-zhangzara-raw-grid', '设计打磨', '网页'),
    ('html-ppt-zhangzara-block-frame', '设计打磨', '网页'),
    ('hatch-pet', '个人主页', '图片'),
    ('3d-stone-staircase-evolution-infographic', '图片', '图片'),
    ('notion-team-dashboard-live-artifact', '图片', '图片'),
    ('vr-headset-exploded-view-poster', '图片', '图片'),
    ('profile-avatar-cinematic-south-asian-male-portrait-with-vultures', '图片', '图片'),
    ('profile-avatar-realistically-imperfect-ai-selfie', '图片', '图片'),
    ('profile-avatar-signed-marker-portrait-on-shikishi', '图片', '图片'),
    ('profile-avatar-poetic-woman-in-garden-portrait', '图片', '图片'),
    ('profile-avatar-hyper-realistic-selfie-texture-prompts', '图片', '图片'),
    ('profile-avatar-casual-fashion-grid-photoshoot', '图片', '图片'),
    ('profile-avatar-professional-identity-portrait-wallpaper', '图片', '图片'),
    ('infographic-otaku-dance-choreography-breakdown-gokurakujodo-16-panels', '图片', '图片'),
    ('anime-martial-arts-battle-illustration', '图片', '图片'),
    ('profile-avatar-song-dynasty-hanfu-portrait', '图片', '图片'),
    ('profile-avatar-monochrome-studio-portrait', '图片', '图片'),
    ('profile-avatar-elegant-fantasy-girl-in-violet-garden', '图片', '图片'),
    ('profile-avatar-lavender-fantasy-mage-portrait', '图片', '图片'),
    ('profile-avatar-snowy-rabbit-hanfu-portrait', '图片', '图片'),
    ('profile-avatar-glamorous-woman-in-black-portrait', '图片', '图片'),
    ('profile-avatar-cyberpunk-anime-portrait-with-neon-face-text', '图片', '图片'),
    ('profile-avatar-snowy-rabbit-spirit-portrait', '图片', '图片'),
    ('profile-avatar-anime-girl-to-cinematic-photo', '图片', '图片'),
    ('profile-avatar-ethereal-blue-haired-fantasy-portrait', '图片', '图片'),
    ('profile-avatar-old-photo-restoration-to-dslr-portrait', '图片', '图片'),
    ('profile-avatar-snow-rabbit-mask-hanfu-portrait', '图片', '图片'),
    ('profile-avatar-snow-rabbit-empress-portrait', '图片', '图片'),
    ('illustrated-city-food-map', '图片', '图片'),
    ('illustration-crayon-kid-drawing-rework', '图片', '图片'),
    ('momotaro-explainer-slide-in-hybrid-style', '图片', '图片'),
    ('game-ui-ancient-china-open-world-mmo-hud', '图片', '图片'),
    ('game-screenshot-three-kingdoms-zhaoyun-cradle-escape', '图片', '图片'),
    ('game-screenshot-three-kingdoms-guanyu-slaying-yanliang', '图片', '图片'),
    ('game-screenshot-three-kingdoms-lyubu-yuanmen-archery', '图片', '图片'),
    ('game-screenshot-anime-fighting-game-captain-ryuuga-vs-kaze-renshin', '图片', '图片'),
    ('e-commerce-live-stream-ui-mockup', '图片', '图片'),
    ('social-media-post-psg-transfer-announcement-poster', '图片', '图片'),
    ('social-media-post-anime-pokemon-shop-outfit-teaser-poster', '图片', '图片'),
    ('social-media-post-confused-elf-girl-at-pastel-desk', '图片', '图片'),
    ('social-media-post-vintage-sign-painter-sketch', '图片', '图片'),
    ('social-media-post-sensational-girl-dance-storyboard-8-shots', '图片', '图片'),
    ('social-media-post-travel-snapshot-collage-prompt', '图片', '图片'),
    ('social-media-post-fashion-editorial-collage', '图片', '图片'),
    ('social-media-post-editorial-fashion-photography', '图片', '图片'),
    ('social-media-post-showa-day-retro-culture-magazine-cover', '图片', '图片'),
    ('social-media-post-cinematic-elevator-scene', '图片', '图片'),
    ('social-media-post-social-media-fashion-outfit-generation', '图片', '图片'),
    ('image-poster', '设计与创意', '图片'),
    ('video-shortform', '落地页与营销', '视频'),
    ('3d-animated-boy-building-lego', '视频', '视频'),
    ('hyperframes', '视频', '视频'),
    ('video-hyperframes', '视频', '视频'),
    ('frame-nyt-graph', '视频', 'HyperFrames'),
    ('frame-data-chart-nyt', '视频', '视频'),
    ('frame-data-chart-nyt-video', '视频', 'HyperFrames'),
    ('cinematic-street-racing-sequence-for-seedance-2', '视频', '视频'),
    ('seedance-2-0-15-second-cinematic-japanese-romance-short-film', '视频', '视频'),
    ('seedance-2-0-80-year-old-rapper-mv', '视频', '视频'),
    ('vfx-text-cursor', '视频', '视频'),
    ('vfx-text-cursor-video', '视频', 'HyperFrames'),
    ('video-seedance-desk-hologram-ar-realdesk', '视频', '视频'),
    ('frame-macos-notification', '视频', '视频'),
    ('cinematic-east-asian-woman-hand-dance', '视频', '视频'),
    ('frame-takram-organic', '视频', 'HyperFrames'),
    ('frame-product-promo', '视频', 'HyperFrames'),
    ('frame-product-promo-30s', '视频', 'HyperFrames'),
    ('traditional-dance-performance', '视频', '视频'),
    ('frame-decision-tree', '视频', 'HyperFrames'),
    ('frame-creative-voltage', '视频', 'HyperFrames'),
    ('frame-kinetic-type', '视频', 'HyperFrames'),
    ('animation-transfer-and-camera-tracking-prompt', '视频', '视频'),
    ('a-decade-of-refinement-glow-up', '视频', '视频'),
    ('ancient-indian-kingdom-fpv-video', '视频', '视频'),
    ('frame-logo-outro', '视频', '视频'),
    ('frame-logo-outro-video', '视频', 'HyperFrames'),
    ('retro-hk-wuxia-film-aesthetic', '视频', '视频'),
    ('vintage-disney-style-pirate-crocodile-animation', '视频', '视频'),
    ('nightclub-flyer-atmospheric-animation', '视频', '视频'),
    ('frame-bold-signal', '视频', 'HyperFrames'),
    ('frame-bold-poster', '视频', 'HyperFrames'),
    ('frame-build-minimal', '视频', 'HyperFrames'),
    ('hollywood-haute-couture-fantasy-video-prompt', '视频', '视频'),
    ('frame-glitch-title', '视频', '视频'),
    ('frame-glitch-title-video', '视频', 'HyperFrames'),
    ('frame-data-rollup', '视频', 'HyperFrames'),
    ('frame-warm-grain', '视频', 'HyperFrames'),
    ('sequence-and-movement-instruction-for-martial-arts-video', '视频', '视频'),
    ('frame-liquid-bg-hero', '视频', '视频'),
    ('frame-liquid-bg-hero-video', '视频', 'HyperFrames'),
    ('crimson-horizon-sci-fi-cinematic-sequence', '视频', '视频'),
    ('soul-switching-mirror-magic-sequence', '视频', '视频'),
    ('toaster-rocket-jumpscare', '视频', '视频'),
    ('frame-play-mode', '视频', 'HyperFrames'),
    ('modern-rural-aesthetics-healing-short-film-video-prompt', '视频', '视频'),
    ('frame-swiss-grid', '视频', 'HyperFrames'),
    ('frame-pentagram-stat', '视频', 'HyperFrames'),
    ('frame-electric-studio', '视频', 'HyperFrames'),
    ('cinematic-birthday-celebration-sequence', '视频', '视频'),
    ('cinematic-emotional-face-close-up', '视频', '视频'),
    ('cinematic-marine-biologist-exploration', '视频', '视频'),
    ('cinematic-route-navigation-guide', '视频', '视频'),
    ('cinematic-dragon-interaction-flight', '视频', '视频'),
    ('cinematic-music-podcast-and-guitar-technique', '视频', '视频'),
    ('cinematic-vampire-alley-fight-sequence', '视频', '视频'),
    ('viral-k-pop-dance-choreography', '视频', '视频'),
    ('live-action-anime-adaptation-water-vs-thunder-breathing-duel', '视频', '视频'),
    ('forbidden-city-cat-satire', '视频', '视频'),
    ('frame-vignelli', '视频', 'HyperFrames'),
    ('frame-light-leak-cinema', '视频', '视频'),
    ('frame-light-leak-cinema-video', '视频', 'HyperFrames'),
    ('beat-synced-outfit-transformation-dance', '视频', '视频'),
    ('wasteland-factory-chase', '视频', '视频'),
    ('video-seedance-three-kingdoms-lyubu-yuanmen-archery', '视频', '视频'),
    ('video-seedance-three-kingdoms-zhaoyun-cradle-escape', '视频', '视频'),
    ('video-seedance-three-kingdoms-guanyu-slaying-yanliang', '视频', '视频'),
    ('character-intro-motion-graphics-sequence', '视频', '视频'),
    ('luxury-supercar-cinematic-narrative', '视频', '视频'),
    ('cyberpunk-game-trailer-script', '视频', '视频'),
    ('ancient-guardian-dragon-rescue', '视频', '视频'),
    ('hunched-character-animation', '视频', '视频'),
    ('magical-academy-storyboard-sequence', '视频', '视频'),
    ('frame-flowchart-sticky', '运营与看板', '视频'),
    ('audio-jingle', '落地页与营销', '音频')
) AS v(slug, category, subcategory)
WHERE r.slug = v.slug
  AND r.workspace_id IS NULL
  AND r.origin = 'builtin';
