-- Restates the built-in recipes' row-two facets with Open Design's own rules.
--
-- Migration 893 used `od.category` (right for decks) but a coarse scenario
-- bucket for every other mode. Open Design does not derive those from a data
-- field at all: plugins-home/facets.ts matches each plugin's tags, scenario
-- and name against a fixed keyword table, first match wins — six buckets for
-- prototypes, six for images, five for videos, and the fifteen commercial
-- categories for decks. This migration ports that table and applies it, so
-- clicking a mode shows the same second row Open Design shows.
--
-- A plugin that matches no rule gets no facet upstream (it appears only under
-- 全部, never as a pill), so `category` is set to '' for those rather than to
-- an invented bucket. `subcategory` is cleared: it held the surface (网页 /
-- 视频 …), which is redundant with the mode row and never a facet upstream.
UPDATE design_scenario_recipe AS r SET
    category = v.category,
    subcategory = NULL,
    updated_at = now()
FROM (VALUES
    ('doc-kami-parchment', '文档 / 报告'),
    ('social-spotify-card', ''),
    ('resume-modern', '文档 / 报告'),
    ('gamified-app', '应用'),
    ('dating-web', '应用'),
    ('mockup-device-3d', '品牌 / 设计'),
    ('pm-spec', '文档 / 报告'),
    ('team-okrs', ''),
    ('eng-runbook', '开发者工具'),
    ('web-clone', ''),
    ('codex-interactive-capability-map', ''),
    ('invoice', '文档 / 报告'),
    ('data-report', '数据看板'),
    ('finance-report', '文档 / 报告'),
    ('kami-landing', ''),
    ('motion-frames', ''),
    ('open-design-homepage', '落地页 / 营销'),
    ('open-design-landing', '落地页 / 营销'),
    ('social-reddit-card', ''),
    ('card-twitter', ''),
    ('social-x-post-card', ''),
    ('pricing-page', '落地页 / 营销'),
    ('blog-post', '落地页 / 营销'),
    ('card-xiaohongshu', ''),
    ('digital-eguide', '落地页 / 营销'),
    ('article-magazine', '落地页 / 营销'),
    ('magazine-poster', ''),
    ('email-marketing', '落地页 / 营销'),
    ('social-carousel', '落地页 / 营销'),
    ('waitlist-page', '落地页 / 营销'),
    ('sprite-animation', ''),
    ('poster-hero', '落地页 / 营销'),
    ('clinical-case-report', '文档 / 报告'),
    ('hr-onboarding', '应用'),
    ('dcf-valuation', '品牌 / 设计'),
    ('html-ppt-taste-brutalist', '品牌 / 设计'),
    ('html-ppt-taste-editorial', '品牌 / 设计'),
    ('velar-luxury-real-estate', '落地页 / 营销'),
    ('webgl-voronoi-cells', '品牌 / 设计'),
    ('web-prototype-taste-brutalist', '品牌 / 设计'),
    ('web-prototype-taste-soft', '品牌 / 设计'),
    ('web-prototype-taste-editorial', '品牌 / 设计'),
    ('webgl-experience', '品牌 / 设计'),
    ('worker-visualizer', '品牌 / 设计'),
    ('x-research', '品牌 / 设计'),
    ('webgl-pixel-reveal-gallery', '品牌 / 设计'),
    ('webgl-raymarched-hero', '品牌 / 设计'),
    ('webgl-holographic-foil', '品牌 / 设计'),
    ('webgl-halftone-drift', '品牌 / 设计'),
    ('webgl-distortion-grain', '品牌 / 设计'),
    ('tweaks', '品牌 / 设计'),
    ('last30days', '品牌 / 设计'),
    ('webgl-aurora-veil', '品牌 / 设计'),
    ('wireframe-annotated', '品牌 / 设计'),
    ('webgl-horizontal-parallax', '品牌 / 设计'),
    ('webgl-caustic-pool', '品牌 / 设计'),
    ('webgl-liquid-metal', '品牌 / 设计'),
    ('webgl-depth-gallery', '品牌 / 设计'),
    ('wireframe-greybox', '品牌 / 设计'),
    ('social-media-dashboard', '数据看板'),
    ('mobile-app', '应用'),
    ('wireframe-mobile-flow', '应用'),
    ('webgl-particle-galaxy', '品牌 / 设计'),
    ('wireframe-sketch', '品牌 / 设计'),
    ('webgl-liquid-iridescence', '品牌 / 设计'),
    ('critique', '品牌 / 设计'),
    ('webgl-neon-grid', '品牌 / 设计'),
    ('flowai-live-dashboard-template', '数据看板'),
    ('github-dashboard', '数据看板'),
    ('orbit-github', '开发者工具'),
    ('orbit-gmail', ''),
    ('orbit-linear', '开发者工具'),
    ('orbit-notion', ''),
    ('orbit-general', ''),
    ('dashboard', '数据看板'),
    ('meeting-notes', ''),
    ('live-dashboard', '数据看板'),
    ('live-artifact', '数据看板'),
    ('kanban-board', ''),
    ('html-ppt-tech-sharing', 'AI 素养'),
    ('html-ppt-obsidian-claude-gradient', 'AI 素养'),
    ('html-ppt-presenter-mode-reveal', 'AI 素养'),
    ('html-ppt-hermes-cyber-terminal', 'AI 素养'),
    ('ve-terminal-mono', 'AI 素养'),
    ('frontend-slides', 'AI 素养'),
    ('fs-electric-studio', 'B2B 销售'),
    ('huashu-takram-soft-tech', 'B2B 销售'),
    ('html-ppt-zhangzara-cobalt-grid', 'B2B 销售'),
    ('html-ppt-product-launch', 'B2B 销售'),
    ('huashu-bento-insight', 'B2B 销售'),
    ('html-ppt-graphify-dark-graph', '产品管理'),
    ('replit-deck', ''),
    ('deck-open-slide-canvas', '产品管理'),
    ('html-ppt-knowledge-arch-blueprint', '产品管理'),
    ('hps-true-blueprint', '产品管理'),
    ('html-ppt', ''),
    ('huashu-keynote-black', '企业战略'),
    ('huashu-annual-letter', '企业战略'),
    ('simple-deck', '企业战略'),
    ('html-ppt-zhangzara-blue-professional', '企业战略'),
    ('html-ppt-zhangzara-signal', '企业战略'),
    ('deck-swiss-international', '企业战略'),
    ('html-ppt-zhangzara-soft-editorial', '咨询顾问'),
    ('ppt-keynote', '咨询顾问'),
    ('huashu-golden-circle', '咨询顾问'),
    ('huashu-luxe-whitespace', '咨询顾问'),
    ('html-ppt-zhangzara-mat', '咨询顾问'),
    ('html-ppt-zhangzara-monochrome', '学术研究'),
    ('html-ppt-zhangzara-vellum', '学术研究'),
    ('kami-deck', '学术研究'),
    ('hps-academic-paper', '学术研究'),
    ('html-ppt-zhangzara-scatterbrain', '学生作业'),
    ('html-ppt-zhangzara-cartesian', '学生作业'),
    ('html-ppt-zhangzara-pin-and-paper', '学生作业'),
    ('fs-notebook-tabs', '学生作业'),
    ('deck-guizang-editorial', '市场增长'),
    ('open-design-landing-deck', '市场增长'),
    ('html-ppt-zhangzara-broadside', '市场增长'),
    ('huashu-pentagram-grid', '市场增长'),
    ('fs-emerald-editorial', '市场增长'),
    ('html-ppt-zhangzara-coral', '市场增长'),
    ('html-ppt-zhangzara-peoples-platform', '政府与政策'),
    ('html-ppt-zhangzara-grove', '政府与政策'),
    ('html-ppt-zhangzara-stencil-tablet', '政府与政策'),
    ('html-ppt-testing-safety-alert', '政府与政策'),
    ('html-ppt-zhangzara-long-table', '数据与财务'),
    ('html-ppt-weekly-report', '数据与财务'),
    ('ve-midnight-editorial', '数据与财务'),
    ('weekly-update', '数据与财务'),
    ('hps-y2k-chrome', '数据与财务'),
    ('huashu-sparkline-arc', '数据与财务'),
    ('hps-memphis-pop', '生活故事'),
    ('html-ppt-xhs-pastel-card', '生活故事'),
    ('html-ppt-zhangzara-pink-script', '生活故事'),
    ('html-ppt-zhangzara-sakura-chroma', '生活故事'),
    ('html-ppt-zhangzara-8-bit-orbit', '生活故事'),
    ('html-ppt-zhangzara-retro-zine', '生活故事'),
    ('hps-retro-tv', '生活故事'),
    ('html-ppt-zhangzara-neo-grid-bold', '职业发展'),
    ('html-ppt-zhangzara-capsule', '职业发展'),
    ('html-ppt-xhs-white-editorial', '职业发展'),
    ('huashu-slides', '职业发展'),
    ('html-ppt-zhangzara-retro-windows', '职业培训'),
    ('hps-bauhaus', '职业培训'),
    ('html-ppt-zhangzara-daisy-days', '职业培训'),
    ('html-ppt-course-module', '职业培训'),
    ('html-ppt-zhangzara-playful', '职业培训'),
    ('guizang-ppt', ''),
    ('html-ppt-zhangzara-bold-poster', '融资路演'),
    ('ib-pitch-book', '融资路演'),
    ('fs-creative-voltage', '融资路演'),
    ('html-ppt-pitch-deck', '融资路演'),
    ('html-ppt-zhangzara-creative-mode', '设计打磨'),
    ('html-ppt-zhangzara-studio', '设计打磨'),
    ('fs-editorial-forest', '设计打磨'),
    ('html-ppt-zhangzara-editorial-tri-tone', '设计打磨'),
    ('html-ppt-zhangzara-biennale-yellow', '设计打磨'),
    ('html-ppt-zhangzara-raw-grid', '设计打磨'),
    ('html-ppt-zhangzara-block-frame', '设计打磨'),
    ('hatch-pet', 'UI / 产品样机'),
    ('3d-stone-staircase-evolution-infographic', '社交 / 内容'),
    ('notion-team-dashboard-live-artifact', 'UI / 产品样机'),
    ('vr-headset-exploded-view-poster', 'UI / 产品样机'),
    ('profile-avatar-cinematic-south-asian-male-portrait-with-vultures', '头像 / 人像'),
    ('profile-avatar-realistically-imperfect-ai-selfie', '头像 / 人像'),
    ('profile-avatar-signed-marker-portrait-on-shikishi', '头像 / 人像'),
    ('profile-avatar-poetic-woman-in-garden-portrait', '头像 / 人像'),
    ('profile-avatar-hyper-realistic-selfie-texture-prompts', '头像 / 人像'),
    ('profile-avatar-casual-fashion-grid-photoshoot', '头像 / 人像'),
    ('profile-avatar-professional-identity-portrait-wallpaper', '品牌 / Logo'),
    ('infographic-otaku-dance-choreography-breakdown-gokurakujodo-16-panels', '分镜'),
    ('anime-martial-arts-battle-illustration', '插画 / 风格'),
    ('profile-avatar-song-dynasty-hanfu-portrait', '头像 / 人像'),
    ('profile-avatar-monochrome-studio-portrait', '头像 / 人像'),
    ('profile-avatar-elegant-fantasy-girl-in-violet-garden', '头像 / 人像'),
    ('profile-avatar-lavender-fantasy-mage-portrait', '头像 / 人像'),
    ('profile-avatar-snowy-rabbit-hanfu-portrait', '头像 / 人像'),
    ('profile-avatar-glamorous-woman-in-black-portrait', '头像 / 人像'),
    ('profile-avatar-cyberpunk-anime-portrait-with-neon-face-text', '头像 / 人像'),
    ('profile-avatar-snowy-rabbit-spirit-portrait', '头像 / 人像'),
    ('profile-avatar-anime-girl-to-cinematic-photo', '头像 / 人像'),
    ('profile-avatar-ethereal-blue-haired-fantasy-portrait', '头像 / 人像'),
    ('profile-avatar-old-photo-restoration-to-dslr-portrait', '头像 / 人像'),
    ('profile-avatar-snow-rabbit-mask-hanfu-portrait', '头像 / 人像'),
    ('profile-avatar-snow-rabbit-empress-portrait', '头像 / 人像'),
    ('illustrated-city-food-map', '插画 / 风格'),
    ('illustration-crayon-kid-drawing-rework', '插画 / 风格'),
    ('momotaro-explainer-slide-in-hybrid-style', '插画 / 风格'),
    ('game-ui-ancient-china-open-world-mmo-hud', 'UI / 产品样机'),
    ('game-screenshot-three-kingdoms-zhaoyun-cradle-escape', 'UI / 产品样机'),
    ('game-screenshot-three-kingdoms-guanyu-slaying-yanliang', 'UI / 产品样机'),
    ('game-screenshot-three-kingdoms-lyubu-yuanmen-archery', 'UI / 产品样机'),
    ('game-screenshot-anime-fighting-game-captain-ryuuga-vs-kaze-renshin', 'UI / 产品样机'),
    ('e-commerce-live-stream-ui-mockup', 'UI / 产品样机'),
    ('social-media-post-psg-transfer-announcement-poster', '品牌 / Logo'),
    ('social-media-post-anime-pokemon-shop-outfit-teaser-poster', '品牌 / Logo'),
    ('social-media-post-confused-elf-girl-at-pastel-desk', '社交 / 内容'),
    ('social-media-post-vintage-sign-painter-sketch', '社交 / 内容'),
    ('social-media-post-sensational-girl-dance-storyboard-8-shots', '分镜'),
    ('social-media-post-travel-snapshot-collage-prompt', '社交 / 内容'),
    ('social-media-post-fashion-editorial-collage', '社交 / 内容'),
    ('social-media-post-editorial-fashion-photography', '社交 / 内容'),
    ('social-media-post-showa-day-retro-culture-magazine-cover', '品牌 / Logo'),
    ('social-media-post-cinematic-elevator-scene', '社交 / 内容'),
    ('social-media-post-social-media-fashion-outfit-generation', '社交 / 内容'),
    ('image-poster', 'UI / 产品样机'),
    ('video-shortform', '营销 / 产品'),
    ('3d-animated-boy-building-lego', ''),
    ('hyperframes', '动效 / 特效'),
    ('video-hyperframes', ''),
    ('frame-nyt-graph', '数据 / 解说'),
    ('frame-data-chart-nyt', '动效 / 特效'),
    ('frame-data-chart-nyt-video', '动效 / 特效'),
    ('cinematic-street-racing-sequence-for-seedance-2', '电影感 / 叙事'),
    ('seedance-2-0-15-second-cinematic-japanese-romance-short-film', '电影感 / 叙事'),
    ('seedance-2-0-80-year-old-rapper-mv', '电影感 / 叙事'),
    ('vfx-text-cursor', '动效 / 特效'),
    ('vfx-text-cursor-video', '动效 / 特效'),
    ('video-seedance-desk-hologram-ar-realdesk', '社交 / 短视频'),
    ('frame-macos-notification', '动效 / 特效'),
    ('cinematic-east-asian-woman-hand-dance', '电影感 / 叙事'),
    ('frame-takram-organic', '数据 / 解说'),
    ('frame-product-promo', '营销 / 产品'),
    ('frame-product-promo-30s', '营销 / 产品'),
    ('traditional-dance-performance', '营销 / 产品'),
    ('frame-decision-tree', '数据 / 解说'),
    ('frame-creative-voltage', ''),
    ('frame-kinetic-type', ''),
    ('animation-transfer-and-camera-tracking-prompt', ''),
    ('a-decade-of-refinement-glow-up', '营销 / 产品'),
    ('ancient-indian-kingdom-fpv-video', '电影感 / 叙事'),
    ('frame-logo-outro', '动效 / 特效'),
    ('frame-logo-outro-video', '动效 / 特效'),
    ('retro-hk-wuxia-film-aesthetic', '营销 / 产品'),
    ('vintage-disney-style-pirate-crocodile-animation', ''),
    ('nightclub-flyer-atmospheric-animation', '电影感 / 叙事'),
    ('frame-bold-signal', ''),
    ('frame-bold-poster', ''),
    ('frame-build-minimal', ''),
    ('hollywood-haute-couture-fantasy-video-prompt', '电影感 / 叙事'),
    ('frame-glitch-title', '动效 / 特效'),
    ('frame-glitch-title-video', '动效 / 特效'),
    ('frame-data-rollup', '数据 / 解说'),
    ('frame-warm-grain', ''),
    ('sequence-and-movement-instruction-for-martial-arts-video', '电影感 / 叙事'),
    ('frame-liquid-bg-hero', '动效 / 特效'),
    ('frame-liquid-bg-hero-video', '动效 / 特效'),
    ('crimson-horizon-sci-fi-cinematic-sequence', '电影感 / 叙事'),
    ('soul-switching-mirror-magic-sequence', '电影感 / 叙事'),
    ('toaster-rocket-jumpscare', ''),
    ('frame-play-mode', ''),
    ('modern-rural-aesthetics-healing-short-film-video-prompt', '电影感 / 叙事'),
    ('frame-swiss-grid', ''),
    ('frame-pentagram-stat', '数据 / 解说'),
    ('frame-electric-studio', ''),
    ('cinematic-birthday-celebration-sequence', '电影感 / 叙事'),
    ('cinematic-emotional-face-close-up', '电影感 / 叙事'),
    ('cinematic-marine-biologist-exploration', '电影感 / 叙事'),
    ('cinematic-route-navigation-guide', '电影感 / 叙事'),
    ('cinematic-dragon-interaction-flight', '电影感 / 叙事'),
    ('cinematic-music-podcast-and-guitar-technique', '电影感 / 叙事'),
    ('cinematic-vampire-alley-fight-sequence', '电影感 / 叙事'),
    ('viral-k-pop-dance-choreography', '社交 / 短视频'),
    ('live-action-anime-adaptation-water-vs-thunder-breathing-duel', '电影感 / 叙事'),
    ('forbidden-city-cat-satire', '电影感 / 叙事'),
    ('frame-vignelli', ''),
    ('frame-light-leak-cinema', '动效 / 特效'),
    ('frame-light-leak-cinema-video', '动效 / 特效'),
    ('beat-synced-outfit-transformation-dance', '电影感 / 叙事'),
    ('wasteland-factory-chase', '电影感 / 叙事'),
    ('video-seedance-three-kingdoms-lyubu-yuanmen-archery', '电影感 / 叙事'),
    ('video-seedance-three-kingdoms-zhaoyun-cradle-escape', '电影感 / 叙事'),
    ('video-seedance-three-kingdoms-guanyu-slaying-yanliang', '电影感 / 叙事'),
    ('character-intro-motion-graphics-sequence', '动效 / 特效'),
    ('luxury-supercar-cinematic-narrative', '电影感 / 叙事'),
    ('cyberpunk-game-trailer-script', '电影感 / 叙事'),
    ('ancient-guardian-dragon-rescue', '电影感 / 叙事'),
    ('hunched-character-animation', ''),
    ('magical-academy-storyboard-sequence', '营销 / 产品'),
    ('frame-flowchart-sticky', '动效 / 特效'),
    ('audio-jingle', '')
) AS v(slug, category)
WHERE r.slug = v.slug
  AND r.workspace_id IS NULL
  AND r.origin = 'builtin';
