CREATE TABLE task_run_evidence (
    task_id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    runtime_id UUID NOT NULL,
    daemon_id TEXT NOT NULL CHECK (char_length(daemon_id) BETWEEN 1 AND 255),
    attempt INTEGER NOT NULL CHECK (attempt > 0),
    revision BIGINT NOT NULL CHECK (revision > 0),
    payload_sha256 TEXT NOT NULL CHECK (payload_sha256 ~ '^sha256:[0-9a-f]{64}$'),

    queue_known BOOLEAN NOT NULL,
    queue_duration_ms BIGINT,
    preparation_known BOOLEAN NOT NULL,
    preparation_duration_ms BIGINT,
    first_tool_known BOOLEAN NOT NULL,
    first_tool_duration_ms BIGINT,
    execution_known BOOLEAN NOT NULL,
    execution_duration_ms BIGINT,
    finalization_known BOOLEAN NOT NULL,
    finalization_duration_ms BIGINT,

    requested_model TEXT,
    requested_effort TEXT,
    client_effective_model TEXT,
    client_effective_effort TEXT,
    provider_reported_model TEXT,
    provider_model_source TEXT NOT NULL,
    runtime_version TEXT,
    runtime_content_sha256 TEXT,

    input_uncached_tokens BIGINT,
    input_cache_read_tokens BIGINT,
    input_cache_write_tokens BIGINT,
    output_tokens BIGINT,
    usage_complete BOOLEAN NOT NULL,
    usage_source TEXT NOT NULL,

    provider_cost_usd_ticks BIGINT,
    provider_cost_complete BOOLEAN NOT NULL,
    provider_cost_authority TEXT NOT NULL,
    provider_cost_basis TEXT NOT NULL,
    provider_cost_source TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CHECK ((queue_known AND queue_duration_ms >= 0) OR (NOT queue_known AND queue_duration_ms IS NULL)),
    CHECK ((preparation_known AND preparation_duration_ms >= 0) OR (NOT preparation_known AND preparation_duration_ms IS NULL)),
    CHECK ((first_tool_known AND first_tool_duration_ms >= 0) OR (NOT first_tool_known AND first_tool_duration_ms IS NULL)),
    CHECK ((execution_known AND execution_duration_ms >= 0) OR (NOT execution_known AND execution_duration_ms IS NULL)),
    CHECK ((finalization_known AND finalization_duration_ms >= 0) OR (NOT finalization_known AND finalization_duration_ms IS NULL)),
    CHECK (requested_model IS NULL OR char_length(requested_model) BETWEEN 1 AND 255),
    CHECK (requested_effort IS NULL OR char_length(requested_effort) BETWEEN 1 AND 64),
    CHECK (client_effective_model IS NULL OR char_length(client_effective_model) BETWEEN 1 AND 255),
    CHECK (client_effective_effort IS NULL OR char_length(client_effective_effort) BETWEEN 1 AND 64),
    CHECK (provider_reported_model IS NULL OR char_length(provider_reported_model) BETWEEN 1 AND 255),
    CHECK (provider_model_source IN ('provider_event', 'provider_summary', 'model_usage', 'missing')),
    CHECK ((provider_model_source = 'missing' AND provider_reported_model IS NULL) OR (provider_model_source <> 'missing' AND provider_reported_model IS NOT NULL)),
    CHECK (runtime_version IS NULL OR (char_length(runtime_version) BETWEEN 1 AND 128 AND runtime_version !~ '[[:cntrl:]/\\]')),
    CHECK (runtime_content_sha256 IS NULL OR runtime_content_sha256 ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (input_uncached_tokens IS NULL OR input_uncached_tokens >= 0),
    CHECK (input_cache_read_tokens IS NULL OR input_cache_read_tokens >= 0),
    CHECK (input_cache_write_tokens IS NULL OR input_cache_write_tokens >= 0),
    CHECK (output_tokens IS NULL OR output_tokens >= 0),
    CHECK (usage_source IN ('provider_event', 'provider_summary', 'model_usage', 'missing')),
    CHECK (NOT usage_complete OR (input_uncached_tokens IS NOT NULL AND input_cache_read_tokens IS NOT NULL AND input_cache_write_tokens IS NOT NULL AND output_tokens IS NOT NULL)),
    CHECK (usage_source <> 'missing' OR (NOT usage_complete AND input_uncached_tokens IS NULL AND input_cache_read_tokens IS NULL AND input_cache_write_tokens IS NULL AND output_tokens IS NULL)),
    CHECK (provider_cost_usd_ticks IS NULL OR provider_cost_usd_ticks >= 0),
    CHECK (provider_cost_authority IN ('provider_reported', 'missing')),
    CHECK (provider_cost_basis IN ('provider_reported', 'unknown', 'missing')),
    CHECK (provider_cost_source IN ('provider_event', 'provider_summary', 'model_usage', 'task_usage_api', 'missing')),
    CHECK (provider_cost_basis <> 'unknown' OR NOT provider_cost_complete),
    CHECK (
        (provider_cost_authority = 'missing' AND provider_cost_basis = 'missing' AND provider_cost_source = 'missing' AND provider_cost_usd_ticks IS NULL AND NOT provider_cost_complete)
        OR
        (provider_cost_authority = 'provider_reported' AND provider_cost_basis IN ('provider_reported', 'unknown') AND provider_cost_source <> 'missing' AND provider_cost_usd_ticks IS NOT NULL)
    )
);
