CREATE TABLE task_pending_input (
    id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    issue_id UUID NOT NULL,
    task_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    runtime_id UUID NOT NULL,
    claim_generation BIGINT NOT NULL CHECK (claim_generation > 0),
    request_key TEXT NOT NULL CHECK (request_key ~ '^sha256:[0-9a-f]{64}$'),
    request_sha256 TEXT NOT NULL CHECK (request_sha256 ~ '^sha256:[0-9a-f]{64}$'),
    version INTEGER NOT NULL CHECK (version = 1),
    state TEXT NOT NULL CHECK (state IN ('open', 'answered', 'cancelled', 'expired')),
    questions JSONB NOT NULL CHECK (jsonb_typeof(questions) = 'array'),
    answers JSONB,
    question_comment_id UUID NOT NULL,
    answer_comment_id UUID,
    answered_by UUID,
    idempotency_key UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '30 minutes'),
    answered_at TIMESTAMPTZ,
    acked_at TIMESTAMPTZ,
    CHECK (answers IS NULL OR jsonb_typeof(answers) = 'object')
);
